from qf_lib.common.tickers.tickers import Ticker


class Order(object):
    """"
    Order generated by a strategy, then processed by PositionSizer and RiskManager.
    Finally executed by ExecutionHandler.
    """

    def __init__(self, ticker: Ticker, quantity: int):
        """
        This __init__ shouldn't be used anywhere beyond this module. User OrderFactory for creating Order objects.
        """
        self.ticker = ticker
        self.quantity = quantity

    def __str__(self):
        string_template = "{:<15} -> Ticker: {:>17}, Quantity: {:>7}".format(
            self.__class__.__name__, self.ticker.as_string(), self.quantity
        )
        return string_template
