language: python

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
        
script:
    - cd docs
    - make html
    - touch build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: docs/build/html