"""Generate release_notes_generated.md from GitHub Releases (verbatim Markdown)."""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

GITHUB_REPO = "quarkfin/qf-lib"
GITHUB_RELEASES_URL = f"https://api.github.com/repos/{GITHUB_REPO}/releases"
OUTPUT_FILENAME = "release_notes_generated.md"


def _github_request(url: str) -> tuple[Any, str | None]:
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "qf-lib-docs",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            link = response.headers.get("Link")
            data = json.loads(response.read().decode("utf-8"))
            return data, _parse_next_link(link)
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError, TimeoutError):
        return None, None


def _parse_next_link(link_header: str | None) -> str | None:
    if not link_header:
        return None
    for part in link_header.split(","):
        section = part.strip()
        if 'rel="next"' in section:
            match = re.search(r"<([^>]+)>", section)
            if match:
                return match.group(1)
    return None


def _fetch_github_releases() -> list[dict[str, Any]]:
    releases: list[dict[str, Any]] = []
    url: str | None = f"{GITHUB_RELEASES_URL}?per_page=100"

    while url:
        data, next_url = _github_request(url)
        if not isinstance(data, list):
            break
        releases.extend(data)
        url = next_url

    return [release for release in releases if not release.get("draft")]


def _heading_anchor(tag: str) -> str:
    """MyST/Sphinx-style anchor for a version heading (must match myst_heading_anchors)."""
    slug = tag.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


_BARE_URL_PATTERN = re.compile(r"(?<!\]\()(?<!<)(https://[^\s\)<>\]]+)")


def _autolink_bare_urls(text: str) -> str:
    """Wrap bare https URLs in angle brackets so MyST keeps them as hyperlinks."""
    return _BARE_URL_PATTERN.sub(r"<\1>", text)


def generate_release_notes(source_dir: str) -> None:
    """Write release_notes_generated.md next to release_notes.rst."""
    output_path = Path(source_dir) / OUTPUT_FILENAME
    releases = _fetch_github_releases()

    if not releases:
        output_path.write_text(
            "\n".join(
                [
                    "<!-- Auto-generated by release_notes.py -->",
                    "",
                    "Could not load GitHub Releases. Set ``GITHUB_TOKEN`` (or ``GH_TOKEN``), "
                    "ensure network access, and rebuild the documentation.",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        return

    parts = [
        "<!-- Auto-generated from GitHub Releases. Markdown bodies are copied verbatim. -->",
        "",
    ]

    for release in releases:
        tag = release.get("tag_name", "")
        published = (release.get("published_at") or "")[:10]
        body = (release.get("body") or "").strip()
        anchor = _heading_anchor(tag)

        parts.append(f"(release-{anchor})=")
        parts.append(f"## {tag}")
        parts.append("")
        if published:
            parts.append(f"**Released:** {published}")
            parts.append("")
        if body:
            parts.append(_autolink_bare_urls(body))
        else:
            pass
        parts.append("")

    output_path.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    generate_release_notes(str(Path(__file__).resolve().parents[1]))
