from enum import Enum


class Currency(Enum):
    """
    Enum which denotes different currencies.
    """

    USD = "U.S. Dollar"
    """United States Dollar"""
    EUR = "Euro"
    """Euro"""
    JPY = "Japanese Yen"
    """Japanese Yen"""
    GBP = "Sterling"
    """British Pound"""
    CNY = "Renminbi"
    """Chinese Yuan"""
    AUD = "Australian Dollar"
    """Australian Dollar"""
    CAD = "Canadian Dollar"
    """Canadian Dollar"""
    CHF = "Swiss Franc"
    """Swiss Franc"""
    HKD = "Hong Kong Dollar"
    """Hong Kong Dollar"""
    SGD = "Singapore dollar"
    "Singapore dollar"
    SEK = "Swedish Krona"
    "Swedish Krona"
    KRW = "South Korean Won"
    """South Korean Won"""
    NOK = "Norwegian Krone"
    "Norwegian Krone"
    NZD = "New Zealand dollar"
    "New Zealand dollar"
    INR = "Indian Rupee"
    "Indian Rupee"
    MXN = "Mexican Peso"
    "Mexican Peso"
    TWD = "New Taiwan Dollar"
    "New Taiwan Dollar"
    ZAR = "South African Dollar"
    "South African Dollar"
    BRL = "Brazilian Real"
    "Brazilian Real"
    DKK = "Danish Krone"
    "Danish Krone"
    PLN = "Polish złoty"
    "Polish złoty"
    BTC = "Bitcoin"
    "Bitcoin"
