name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Cache python modules
        uses: actions/cache@v3
        env:
          cache-name: cache-python-modules
        with:
          path: pip\
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pip dependencies
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e ".[blpapi]" --extra-index-url https://bcms.bloomberg.com/pip/simple/
          pip3 install --force-reinstall MarkupSafe==2.0.1
          pip3 install flake8==5.0.4 pytest
          pip3 install coverage