# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - 'feature/**'

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4 pytest
    - name: Style check
      run: flake8 .
  unit_tests:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[blpapi]" --extra-index-url https://bcms.bloomberg.com/pip/simple/
        pip install --force-reinstall MarkupSafe==2.0.1
        pip install flake8==5.0.4 pytest
        pip install coverage
    - name: Unit tests
      env:
        QUANTFIN_SECRET: ${{ secrets.QUANTFIN_SECRET }}
      run: |
        coverage run -m pytest qf_lib/tests/unit_tests
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        name: qf-lib-codecov
        verbose: true
  backtesting_tests:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Test
        uses: "./.github/workflows/integration_tests_template"
        with:
          subdirectory: backtesting
          quantfin_secrets: ${{ secrets.QUANTFIN_SECRET }}
  data_providers_tests:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Test
        uses: "./.github/workflows/integration_tests_template"
        with:
          subdirectory: data_providers
          quantfin_secrets: ${{ secrets.QUANTFIN_SECRET }}
