# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --force-reinstall MarkupSafe==2.0.1
        pip install flake8 pytest
        pip install coverage
    - name: Style check
      run: flake8 .
    - name: Unit tests
      run: |
        coverage run -m pytest qf_lib_tests/unit_tests
    - name: Integration tests
      run: |
        coverage run -a -m pytest qf_lib_tests/integration_tests
        coverage xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        name: qf-lib-codecov
        verbose: true

